pws-api: https://api.run.pivotal.io
pws-username: replace
pws-password: replace
pws-org: replace
pws-space: replace
artifactory-username: replace
artifactory-password: replace
git-private-key: replace