# Concourse pipeline definition for the user service.
---
resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: latest
resources:
- name: user-microservice
  type: git
  source:
    uri: {{git-source-repository-url}}
    branch: master
    paths:
    - ./continuous-delivery-basics/user-parent/cd-user-microservice
- name: consumer-tests
  type: git
  source:
    uri: {{git-source-repository-url}}
    branch: master
    paths:
    - ./continuous-delivery-basics/user-parent/user-consumer-tests
- name: snapshot
  type: maven-resource
  source:
    url: {{artifactory-url}}
    artifact: cnj:cd-user-microservice:jar
    username: {{artifactory-username}}
    password: {{artifactory-password}}
- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-RC.0
    uri: {{git-version-repository-url}}
    branch: version
    file: user-microservice
    private_key: {{git-version-private-key}}
- name: cf-deploy-release
  type: cf
  source:
    api: {{cf-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: false
- name: pipeline-tasks
  type: git
  source:
    uri: https://github.com/Pivotal-Field-Engineering/pipeline-tasks
    branch: master
jobs:
- name: unit
  max_in_flight: 1
  plan:
  - get: user-microservice
    trigger: true
  - task: unit
    file: user-microservice/continuous-delivery-basics/user-parent/concourse/unit/unit.yml
- name: integration
  plan:
  - aggregate:
    - get: user-microservice
      trigger: true
      passed: [unit]
    - get: consumer-tests
      trigger: true
  - get: version
    params: { pre: RC }
  - task: consumer-tests
    file: user-microservice/continuous-delivery-basics/user-parent/concourse/integration/consumer-tests.yml
  - put: snapshot
    params:
      file: release/cd-user-microservice.jar
      pom_file: user-microservice/continuous-delivery-basics/user-parent/cd-user-microservice/pom.xml
      version_file: version/version
  - put: version
    params: { file: version/version }
- name: release
  serial: true
  plan:
  - get: snapshot
    trigger: true
    passed: [integration]
  - get: user-microservice
    passed: [integration]
  - get: version
    passed: [integration]
  - get: pipeline-tasks
  - task: prepare-manifest
    file: user-microservice/continuous-delivery-basics/user-parent/concourse/release/prepare.yml
    params:
      MF_PATH: ../release-output/cd-user-microservice.jar
      MF_BUILDPACK: java_buildpack
  - task: prepare-release
    file: user-microservice/continuous-delivery-basics/user-parent/concourse/release/release.yml
  - put: cf-deploy-release
    params:
      manifest: task-output/manifest.yml