# Concourse pipeline definition for the user service.
---
resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: latest
resources:
- name: user-microservice
  type: git
  source:
    uri: https://github.com/cloud-native-java/continuous-delivery
    branch: master
    paths:
    - ./continuous-delivery-basics/user-parent/cd-user-microservice
- name: user-integration
  type: git
  source:
    uri: https://github.com/cloud-native-java/continuous-delivery
    branch: master
    paths:
    - ./continuous-delivery-basics/user-parent/user-consumer-tests
- name: snapshot
  type: maven-resource
  source:
    url: https://cloudnativejava.jfrog.io/cloudnativejava/libs-snapshot-local/
    artifact: cnj:cd-user-microservice:jar
    username: {{artifactory-username}}
    password: {{artifactory-password}}
- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-SNAPSHOT.0
    uri: https://github.com/cloud-native-java/continuous-delivery
    branch: master
    file: version
    private_key: {{git-private-key}}
jobs:
- name: unit
  max_in_flight: 1
  plan:
  - get: user-microservice
    trigger: true
  - task: unit
    file: user-microservice/continuous-delivery-basics/user-parent/concourse/unit/unit.yml
- name: integration
  plan:
  - aggregate:
    - get: user-microservice
      trigger: true
      passed: [unit]
    - get: user-integration
      trigger: true
    - get: version
  - put: snapshot
    params:
      file: release/cd-user-microservice.jar
      pom_file: user-microservice/continuous-delivery-basics/user-parent/cd-user-microservice/pom.xml
      version_file: 1.0.0-SNAPSHOT/maven-metadata.xml
  - put: version
    params: { file: 1.0.0-SNAPSHOT/maven-metadata.xml }
  - task: consumer-tests
    file: user-microservice/continuous-delivery-basics/user-parent/concourse/integration/consumer-tests.yml
- name: release
  serial: true
  plan:
    - aggregate:
        - get: user-microservice
          passed: [integration]
    - task: deploy
      file: user-microservice/continuous-delivery-basics/user-parent/concourse/release/release.yml