# Concourse pipeline definition for the account service.
---
resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: latest
resources:
- name: account-microservice
  type: git
  source:
    uri: https://github.com/cloud-native-java/continuous-delivery
    branch: master
    paths:
    - ./continuous-delivery-basics/account-parent/cd-account-microservice
- name: snapshot
  type: maven-resource
  source:
    url: https://cloudnativejava.jfrog.io/cloudnativejava/libs-release-local/
    artifact: cnj:cd-account-microservice:jar
    username: {{artifactory-username}}
    password: {{artifactory-password}}
- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-RC.0
    uri: git@github.com:cloud-native-java/continuous-delivery.git
    branch: version
    file: account-microservice
    private_key: {{git-private-key}}
- name: cf-deploy-release
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: false
- name: pipeline-tasks
  type: git
  source:
    uri: https://github.com/Pivotal-Field-Engineering/pipeline-tasks
    branch: master
jobs:
- name: build
  max_in_flight: 1
  plan:
  - get: account-microservice
    trigger: true
  - task: unit
    file: account-microservice/continuous-delivery-basics/account-parent/concourse/unit/unit.yml
  - get: version
    params: { pre: RC }
  - put: snapshot
    params:
      file: release/cd-account-microservice.jar
      pom_file: account-microservice/continuous-delivery-basics/account-parent/cd-account-microservice/pom.xml
      version_file: version/version
  - put: version
    params: { file: version/version }
- name: release
  serial: true
  plan:
  - get: snapshot
    trigger: true
    passed: [build]
  - get: account-microservice
    passed: [build]
  - get: version
    passed: [build]
  - get: pipeline-tasks
  - task: prepare-manifest
    file: account-microservice/continuous-delivery-basics/account-parent/concourse/release/prepare.yml
    params:
      MF_PATH: ../release-output/cd-account-microservice.jar
      MF_BUILDPACK: java_buildpack
  - task: prepare-release
    file: account-microservice/continuous-delivery-basics/account-parent/concourse/release/release.yml
  - put: cf-deploy-release
    params:
      manifest: task-output/manifest.yml